MAINT: Update deprecated `seaborn` function calls before they error
Fix deprecated `seaborn` function calls: use `displot` or `histplot`
where applicable instead of `distplot`, since the latter will be removed
in `seaborn` v0.14.0.

Adapt the corresponding calls where necessary adding reasonable keyword
argument values.

Test histogram/distribution nuisance reportlet functions that use the
affected functions.

Fixes:
```
This function has been deprecated and will be removed in seaborn v0.14.0.
It has been replaced by :func:`histplot` and :func:`displot`,
two functions with a modern API and many more capabilities.
```

Documentation:
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

Fix the `mean_fd_hist` checks: use `is not None` as the default value is
`None` and the parameter value is expected to be an array.

Fixes:
```
  File "src/nireports/nireports/reportlets/nuisance.py", line 70, in plot_fd
    if mean_fd_dist:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Raised locally when running the tests.

Adapt the frame-wise displacement LaTeX text to avoid issues in Python
3.9: do not use a raw string.

Fixes:
```
 E           ValueError:
 E           \overline{\text{FD}}
 E                     ^
 E           Unknown symbol: \text, found '\'  (at char 10), (line:1, col:11)
```

raised for example at:
https://github.com/nipreps/nireports/actions/runs/13558179140/job/37896446773?pr=171#step:14:551

Co-authored-by: Chris Markiewicz <effigies@gmail.com>
Co-authored-by: Oscar Esteban <code@oscaresteban.es>